#pragma once

// This is a wrapper around the autogenerated config_definitions.h
// to add some static includes

#include "config_definitions.h"

#include <vlc_fixups.h>

#if defined(_MSC_VER) && !defined(__clang__)
    #pragma fenv_access(off)
    #pragma fp_contract(on)
#elif defined(__GNUC__)
    // Not supported so far
#else
    #pragma STDC FENV_ACCESS OFF
    #pragma STDC FP_CONTRACT ON
#endif

#ifndef _REENTRANT
    #define _REENTRANT
#endif

#if defined(_WIN32) && !defined(_WIN32_WINNT)
    // Windows 7
    #define _WIN32_WINNT 0x0601
#endif


// AH_TEMPLATE(socklen_t, [Define to `int' if <sys/socket.h> does not define.])
// AH_TEMPLATE(sockaddr_storage, [Define to `sockaddr' if <sys/socket.h> does not define.]) dnl ` (fix VIM syntax highlight
// AH_TEMPLATE(ss_family, [Define to `sa_family' if <sys/socket.h> does not define.]) dnl ` (fix VIM syntax highlight
// AH_TEMPLATE(ssize_t, [Define to `int' if <stddef.h> does not define.]) dnl ` (fix VIM syntax highlight
// AH_TEMPLATE(NDEBUG, [Define to 1 if debug code should NOT be compiled])

